spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
